stages:
- build
- test
- deploy

image: ruby:2.5.1

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  LC_ALL: C.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  RAILS_ENV: test

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

rubocop:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull $TEST_IMAGE
    - docker run --rm -e RAILS_ENV=test $TEST_IMAGE bin/bundle exec rubocop

rspec:
  stage: test
  image: $TEST_IMAGE
#  services:
#    - docker:dind
  script:
#    - docker pull $TEST_IMAGE
    - docker run --rm -e RAILS_ENV=test $TEST_IMAGE /bin/bash -c 'bin/bundle exec rake db:create db:test:prepare && rspec'

#deploy:
#  stage: deploy
#  image: docker:latest
#  services:
#    - docker:dind
#  script:
#    - docker pull $TEST_IMAGE
#  only:
#  - master
