require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
  TargetRubyVersion: 2.7
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
