version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    command: bash -c "bin/bundle exec rake db:create db:migrate db:seed && bin/bundle exec puma -p 3000"
    ports:
      - 3000:3000
