version: "3"

services:
  app:
    image: registry.gitlab.com/exsemt/table_go_example:latest
    command: bash -c "RAILS_ENV=production bin/bundle exec rake db:create db:migrate db:seed assets:precompile && bin/bundle exec puma -p 3030"
    environment:
      VIRTUAL_HOST: table-go-example.exsemt.de
      RAILS_ENV: production
    network_mode: bridge
    ports:
      - "3030:3030"

  # or execute on server only with docker:
  # docker run -e VIRTUAL_HOST=table-go-example.exsemt.de -d -it -p 3030:3030 -e RAILS_ENV=production registry.gitlab.com/exsemt/table_go_example:latest /bin/bash -c 'bin/bundle exec rake db:create db:migrate db:seed assets:precompile && rails s'
